---
title: "제목"
author: "이상호"
date: "`r Sys.Date()`"
output:
  word_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 제목
- 내용
  - 세부 내용

## 제목
- 내용
  - 세부 내용

```{r}
# 코드와 결과
summary(cars)
```

```{r, echo=FALSE}
# 결과만
summary(cars)
```

# 01주차
- 변수와 벡터
```{r}
"Hellow World"
print("Hellow World")
cat("Hellow World")
```

# 01주차
- 변수와 벡터
```{r}
# ==============================================================================
# 2023.11.04
# ==============================================================================
# 주석: Ctrl + Shift + C
# 1줄 실행 : Ctrl + Enter

# 다양한 출력
"Hellow World"
print("Hellow World")
cat("Hellow World", "\n")

# 계산기 사용
2 + 3
(3 + 6) * 8

# 사칙연산자: +, -, *, /, ^
# 덧셈
2 + 2

# 뺼셈
2 - 2

# 곱셈
2 * 2

# 나누기
2 / 2

# 거듭제곱
2 ^ 2

# 함수 사용하기
# 로그함수
log(10) + 5

# 제곱근
sqrt(25)

# 최대값
max(5, 3)

# 변수 저장
# 숫자, 문자, T/F 논리
A <- 10
B <- A + 20
cat(A, B)

# <- 대신 = 허용
A = 10
B = 20

# 자료형
# 숫자
# 문자
str = ""

# 논리형
isFlag = TRUE
isFlag = T

# 특수값
# 빈값
NULL

# 결측값
NA

# 수학적으로 정의 불가
NaN

# 무한대
Inf

# 그냥 출력
10 * 10 * 3.14

# 변수에 저장하여 출력
rad = 10
PI = 3.14

(rad ^ 2) * PI

# 벡터 만들기

# 변수로 설정하기 어려움
# 이에 벡터 사용
# x1 = 1
# x2 = 2
# x3 = 3

# 숫자형 벡터
x = c(1, 2, 3)

# 문자열 벡터
y = c("1", "2", "3")

# 연속형 숫자
# v1 = c(50, 51, 52, 53)

# 간격 1 고정
v1 = 50:90

# 시작, 종료, 간격
v3 = seq(1, 100, 3)
v3 = c(1, 4, 7, 10)

# 반복함수
rep(1, times = 5)

rep(1:5, times = 5)

# rep(1, each = 5)
rep(1:5, each = 5)

score = c(90, 85)
names(score) = c("lee", "tom")
score

# 벡터에서 1번 인덱스 추출
score[1]
names(score[1])

# 결측값을 제거하고 합계
sum(score, na.rm = TRUE)
mean(score, na.rm = TRUE)

# 함수 (매개변수명 = 값)

# lee tom 
# 90  85 
# 85 이상인 점수 추출
score > 85
score[score > 85]


sum
# 도움말
help(sum)
?sum

sum(1:5)
sum(1, 2, 3, 4, 5)
```


# 02주차
- 매트릭스와 데이터프레임, 파일 데이터
```{r}


